BEGIN TRANSACTION;

CREATE TABLE Students (
    id INTEGER PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
	birthday DATETIME NOT NULL,
	sex TEXT NOT NULL,
	room INTEGER NOT NULL,
	FOREIGN KEY (room) REFERENCES Rooms(id)
);

COMMIT;
